# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Opportunity',
        ),
    ]
