# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20180412_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunites'},
        ),
    ]
